export default [
  { "label": "大钢琴（声学钢琴）", "value": 0 },
  { "label": "明亮的钢琴", "value": 1 },
  { "label": "电钢琴", "value": 2 },
  { "label": "酒吧钢琴", "value": 3 },
  { "label": "柔和的电钢琴", "value": 4 },
  { "label": "加合唱效果的电钢琴", "value": 5 },
  { "label": "羽管键琴（拨弦古钢琴）", "value": 6 },
  { "label": "科拉维科特琴（击弦古钢琴）", "value": 7 },
  { "label": "钢片琴", "value": 8 },
  { "label": "钟琴", "value": 9 },
  { "label": "八音盒", "value": 10 },
  { "label": "颤音琴", "value": 11 },
  { "label": "马林巴琴", "value": 12 },
  { "label": "木琴", "value": 13 },
  { "label": "管钟", "value": 14 },
  { "label": "大扬琴", "value": 15 },
  { "label": "击杆风琴", "value": 16 },
  { "label": "打击式风琴", "value": 17 },
  { "label": "摇滚风琴", "value": 18 },
  { "label": "教堂风琴", "value": 19 },
  { "label": "簧管风琴", "value": 20 },
  { "label": "手风琴", "value": 21 },
  { "label": "口琴", "value": 22 },
  { "label": "探戈手风琴", "value": 23 },
  { "label": "尼龙弦吉他", "value": 24 },
  { "label": "钢弦吉他", "value": 25 },
  { "label": "爵士电吉他", "value": 26 },
  { "label": "清音电吉他", "value": 27 },
  { "label": "闷音电吉他", "value": 28 },
  { "label": "加驱动效果的电吉他", "value": 29 },
  { "label": "加失真效果的电吉他", "value": 30 },
  { "label": "吉他和音", "value": 31 },
  { "label": "大贝司（声学贝司）", "value": 32 },
  { "label": "电贝司（指弹）", "value": 33 },
  { "label": "电贝司（拨片）", "value": 34 },
  { "label": "无品贝司", "value": 35 },
  { "label": "掌击贝司 1", "value": 36 },
  { "label": "掌击贝司 2", "value": 37 },
  { "label": "电子合成贝司 1", "value": 38 },
  { "label": "电子合成贝司 2", "value": 39 },
  { "label": "小提琴", "value": 40 },
  { "label": "中提琴", "value": 41 },
  { "label": "大提琴", "value": 42 },
  { "label": "低音大提琴", "value": 43 },
  { "label": "弦乐群颤音", "value": 44 },
  { "label": "弦乐群拨弦", "value": 45 },
  { "label": "竖琴", "value": 46 },
  { "label": "定音鼓", "value": 47 },
  { "label": "弦乐合奏1", "value": 48 },
  { "label": "弦乐合奏2", "value": 49 },
  { "label": "合成弦乐合奏1", "value": 50 },
  { "label": "合成弦乐合奏2", "value": 51 },
  { "label": "人声合唱“啊”", "value": 52 },
  { "label": "人声“嘟”", "value": 53 },
  { "label": "合成人声", "value": 54 },
  { "label": "管弦乐敲击齐奏", "value": 55 },
  { "label": "小号", "value": 56 },
  { "label": "长号", "value": 57 },
  { "label": "大号", "value": 58 },
  { "label": "加弱音器小号", "value": 59 },
  { "label": "法国号（圆号）", "value": 60 },
  { "label": "铜管组（铜管乐器合奏音色）", "value": 61 },
  { "label": "合成铜管音色1", "value": 62 },
  { "label": "合成铜管音色2", "value": 63 },
  { "label": "高音萨克斯风", "value": 64 },
  { "label": "次中音萨克斯风", "value": 65 },
  { "label": "中音萨克斯风", "value": 66 },
  { "label": "低音萨克斯风", "value": 67 },
  { "label": "双簧管", "value": 68 },
  { "label": "英国管", "value": 69 },
  { "label": "巴松（大管）", "value": 70 },
  { "label": "单簧管（黑管）", "value": 71 },
  { "label": "短笛", "value": 72 },
  { "label": "长笛", "value": 73 },
  { "label": "竖笛", "value": 74 },
  { "label": "排箫", "value": 75 },
  { "label": "芦笛", "value": 76 },
  { "label": "日本尺八", "value": 77 },
  { "label": "口哨声", "value": 78 },
  { "label": "奥卡雷那", "value": 79 },
  { "label": "合成主音1（方波）", "value": 80 },
  { "label": "合成主音2（锯齿波）", "value": 81 },
  { "label": "合成主音3", "value": 82 },
  { "label": "合成主音4", "value": 83 },
  { "label": "合成主音5", "value": 84 },
  { "label": "合成主音6（人声）", "value": 85 },
  { "label": "合成主音7（平行五度）", "value": 86 },
  { "label": "合成主音8（贝司加主音）", "value": 87 },
  { "label": "合成音色1（新世纪）", "value": 88 },
  { "label": "合成音色2 （温暖）", "value": 89 },
  { "label": "合成音色3", "value": 90 },
  { "label": "合成音色4 （合唱）", "value": 91 },
  { "label": "合成音色5", "value": 92 },
  { "label": "合成音色6 （金属声）", "value": 93 },
  { "label": "合成音色7 （光环）", "value": 94 },
  { "label": "合成音色8", "value": 95 },
  { "label": "合成效果 1 雨声", "value": 96 },
  { "label": "合成效果 2 音轨", "value": 97 },
  { "label": "合成效果 3 水晶", "value": 98 },
  { "label": "合成效果 4 大气", "value": 99 },
  { "label": "合成效果 5 明亮", "value": 100 },
  { "label": "合成效果 6 鬼怪", "value": 101 },
  { "label": "合成效果 7 回声", "value": 102 },
  { "label": "合成效果 8 科幻", "value": 103 },
  { "label": "西塔尔（印度）", "value": 104 },
  { "label": "班卓琴（美洲）", "value": 105 },
  { "label": "三昧线（日本）", "value": 106 },
  { "label": "十三弦筝（日本）", "value": 107 },
  { "label": "卡林巴", "value": 108 },
  { "label": "风笛", "value": 109 },
  { "label": "民族提琴", "value": 110 },
  { "label": "山奈", "value": 111 },
  { "label": "叮当铃", "value": 112 },
  { "label": "Agogo", "value": 113 },
  { "label": "钢鼓", "value": 114 },
  { "label": "木鱼", "value": 115 },
  { "label": "太鼓", "value": 116 },
  { "label": "通通鼓", "value": 117 },
  { "label": "合成鼓", "value": 118 },
  { "label": "铜钹", "value": 119 },
  { "label": "吉他换把杂音", "value": 120 },
  { "label": "呼吸声", "value": 121 },
  { "label": "海浪声", "value": 122 },
  { "label": "鸟鸣", "value": 123 },
  { "label": "电话铃", "value": 124 },
  { "label": "直升机", "value": 125 },
  { "label": "鼓掌声", "value": 126 },
  { "label": "枪声", "value": 127 }
];
