export default {
  // 全局功能性函数
  GetHttpUrl: '/GetHttpUrl',
  Compile:'POST /compile',

  // 学校信息管理
  LoginAdmin: 'POST /LoginAdmin',
  LoginTeacher: "POST /LoginTeacher",
  AddSchool: "POST /AddSchool",
  DelSchool: "POST /DelSchool",
  EditSchool: "POST /EditSchool",
  SchoolList: "/SchoolList",
  AddCollege: "POST /AddCollege",
  DelCollege: "POST /DelCollege",
  EditCollege: "POST /EditCollege",
  GetCollegeBySchoolId: "/GetCollegeBySchoolId",
  GetCollegeListAll: "/GetCollegeListAll",
  AddStand: "POST /AddStand",
  DelStand: "POST /DelStand",
  EditStand: "POST /EditStand",
  GetStandListBySchoolId: "/GetStandListBySchoolId",
  AddMajor: "POST /AddMajor",
  DelMajor: "POST /DelMajor",
  EditMajor: "POST /EditMajor",
  GetMajorBySchoolId: "/GetMajorBySchoolId",
  GetMajorByCollegeId: "/GetMajorByCollegeId",
  AddClass: "POST /AddClass",
  DelClass: "POST /DelClass",
  EditClass: "POST /EditClass",
  GetClassBySchoolId: "/GetClassBySchoolId",
  GetClassByMajorId: "/GetClassByMajorId",
  AddStudent: "POST /AddStudent",
  DelStudent: "POST /DelStudent",
  EditStudent: "POST /EditStudent",
  EditStudentPassWordById: "POST /EditStudentPassWordById",
  GetStudentViewList: "/GetStudentViewList",
  MatchDelStudent: "POST /MatchDelStudent",
  GetClassStudentsBySchoolIdAPI: "GET /GetClassStudentsBySchoolId",
  MatchAddStudentIDImgAPI: "POST /MatchAddStudentIDImg",
  MatchAddSocietyStudentExecl: "POST /MatchAddSocietyStudentExecl",
  GetStudentExeclData: "POST /GetStudentExeclData",
  MatchAddStudent: "POST /MatchAddStudent",

  //↓↓↓↓↓↓↓↓↓教师用户管理相关
  GetTeacherListAPI: "GET /GetTeacherList",
  GetTeacherInfoByIdAPI: "GET /GetTeacherById",
  AddTeacherAPI: "POST /AddTeacher",
  EditTeacherAPI: "POST /EditTeacher",
  DeleteTeacherAPI: "POST /DelTeacher",
  ReSetStudentPassWord: "POST /ReSetStudentPassWord",
  EditTeacherPassWordByIdAPI: "POST /EditTeacherPassWordById",
  //↑↑↑↑↑↑↑教师用户管理相关

  //↓↓↓↓↓↓↓↓↓课程相关
  GetCourseListByTeacherIdAPI: "GET /GetCourseListByTeacherId",
  GetCourseByCourseIdAPI: "GET /GetCourseByCourseId",
  GetCourseClassRelationByIdAPI: "GET /GetCourseClassRelationById",
  AddCourseAPI: "POST /AddCourse",
  EditCourseAPI: "POST /EditCourse",
  EditClassRelationAPI: "POST /EditClassRelation",
  EditCourseFileAPI: "POST /EditCourseFile",
  DelCourseAPI: "POST /DelCourse",
  CourseCancel: "POST /CourseCancel",

  GetChapterByCourseId: "/GetChapterByCourseId",
  GetChapterById: "/GetChapterById",
  AddChapter: "POST /AddChapter",
  EditChapter: "POST /EditChapter",
  DelChapter: "POST /DelChapter",
  UploadChapterVideoFile: "POST /UploadChapterVideoFile",
  UploadChapterFile: "POST /UploadChapterFile",
  UpdateChapterOrder: "POST /UpdateChapterOrder",
  GetCouresStudyPlanByCourseId: "/GetCouresStudyPlanByCourseId",
  //↑↑↑↑↑↑↑课程相关

  //↓↓↓↓↓↓↓↓↓题目相关
  AddQuestion: "POST /AddQuestion",
  EditQuestion: "POST /EditQuestion",
  DelQuestion: "POST /DelQuestion",
  GetQuestionBySchoolId: "/GetQuestionBySchoolId",
  GetExamQuestionBySchoolId: "/GetExamQuestionBySchoolId",
  GetQuestionByQuestionId: "/GetQuestionByQuestionId",
  GetQuestionExeclData: "POST /GetQuestionExeclData",
  MatchAddQuestion: "POST /MatchAddQuestion",
  GetOperPracticeByQuestionId: "/GetOperPracticeByQuestionId",
  //↑↑↑↑↑↑↑题目相关

  //试卷
  GetTestPaperBySchoolId: "/GetTestPaperBySchoolId",
  GetTestPaperByTestPaperId: "/GetTestPaperByTestPaperId",
  GetTestPaperByPaperId: "/GetTestPaperByPaperId",
  AddTestPaper: "POST /AddTestPaper",
  EditTestPaper: "POST /EditTestPaper",
  DelTestPaper: "POST /DelTestPaper",

  // 考试
  AddExam: "POST /AddExam",
  DelExam: "POST /DelExam",
  EditExam: "POST /EditExam",
  ExamCancel: "POST /ExamCancel",
  AddExamSession: "POST /AddExamSession",
  EditExamSession: "POST /EditExamSession",
  DelExamSession: "POST /DelExamSession",
  AddExamStudent: "POST /AddExamStudent",
  EditExamStudent: "POST /EditExamStudent",
  GetExamBySchoolId: "/GetExamBySchoolId",
  GetExamByExamId: "/GetExamByExamId",
  AddExamNotice: "POST /AddExamNotice",
  EditExamNotice: "POST /EditExamNotice",
  DelExamNotice: "POST /DelExamNotice",
  GetExamNoticeByExamId: "/GetExamNoticeByExamId",
  AddExamBatchSessionStudent: "POST /AddExamBatchSessionStudent",
  //考试成绩
  GetExamOverView: "/GetExamOverView",
  GetExamSessionResult: "/GetExamSessionResult",
  //学生考试成绩
  // GetStudentExamPaperOverAPI: 'GET /GetStudentExamPaperOver',//StudentId=6&ExamSessionId=1&ExamId=1
  // 补考
  AddExamReset: "POST /AddExamReset",
  GetCurrentExamSessionBKStudent: "/GetCurrentExamSessionBKStudent",
  GetExamResetByExamSessionId: "/GetExamResetByExamSessionId",
  // 考试审批
  GetExamReViewBySchoolId: "/GetExamReViewBySchoolId",
  EditReViewExamByExamId: "POST /EditReViewExamByExamId",

  // 学习考试计划
  AddPlan: "POST /AddPlan",
  EditPlan: "POST /EditPlan",
  DelPlan: "POST /DelPlan",
  QueryPlan: "/QueryPlan",
  AddPlanStudent: "POST /AddPlanStudent",
  DelPlanStudent: "POST /DelPlanStudent",
  DelAllPlanStudent: "POST /DelAllPlanStudent",
  QueryPlanStudent: "/QueryPlanStudent",
  AddPlanExam: "POST /AddPlanExam",
  DelPlanExam: "POST /DelPlanExam",
  DelAllPlanExam: "POST /DelAllPlanExam",
  QueryPlanExam: "/QueryPlanExam",
  AddPlanTrain: "POST /AddPlanTrain",
  DelPlanTrain: "POST /DelPlanTrain",
  DelAllPlanTrain: "POST /DelAllPlanTrain",
  QueryPlanTrain: '/QueryPlanTrain',
  QueryPlanCourseProgress: '/QueryPlanCourseProgress',
  QueryPlanExamProgress: '/QueryPlanExamProgress',
  QueryPlanTrainProgress: '/QueryPlanTrainProgress',
  AddExamBatchPlanStudent: "POST /AddExamBatchPlanStudent",

  //↓↓↓↓↓↓↓↓↓公告相关
  AddNoticeAPI: "POST /AddNotice",
  EditNoticeAPI: "POST /EditNotice",
  DeleteNoticeAPI: "POST /DelNotice",
  GetNotice5API: "GET /NoticeList",
  GetNoticeAllAPI: "GET /NoticeListAll",
  //↑↑↑↑↑↑↑公告相关
}
